# Generated by Django 5.2.17 on 2026-09-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startedAt', models.DateTimeField(verbose_name='开始时刻')),
                ('plannedReleaseDate', models.DateField(verbose_name='计划解除日')),
                ('faultSummary', models.CharField(max_length=200, verbose_name='故障摘要')),
                ('releasedAt', models.DateTimeField(blank=True, null=True, verbose_name='实解时刻')),
                ('hearth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_seals', to='kiln.firehearth', verbose_name='灶台')),
                ('sealedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_seals', to=settings.AUTH_USER_MODEL, verbose_name='挂条人')),
            ],
            options={
                'verbose_name': '检修封条',
                'verbose_name_plural': '检修封条',
                'ordering': ['-startedAt', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('releasedAt__isnull', True)), fields=('hearth',), name='uniq_active_seal_per_hearth')],
            },
        ),
    ]
